config/routes.rb
Rails.application.routes.draw do

  root 'meets#index'

  get 'sign_up' => 'users#new', :as => 'sign_up'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'

  resources :users, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]

  resources :athletes
  resources :meets, :except => [:edit, :update] do
    member do
      get 'pdf'
      get 'csv'
    end
  end
  resources :heats, :only => [:show, :update]
end

app/models/athlete.rb
class Athlete < ActiveRecord::Base
  scope :active,       -> { where(:status => 'active').order(:first_name, :last_name)}
  scope :active_men,   -> { active.where(:gender => 'men')}
  scope :active_women, -> { active.where(:gender => 'women')}

  STATUS_LIST = ['active', 'inactive']
  GENDER_LIST = ['women', 'men']

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :status
  validates_presence_of :gender

  has_many :swims
  has_many :heats, :through => :swims
  has_many :events, :through => :heats

  def full_name
    format('%{first} %{last}', :first => first_name, :last => last_name).strip
  end

  def entry_counts_for_meet(meet)
    individual, relay = [0, 0]
    self.heats.where(:meet_id => meet.id).each do |h|
      h.event.relay ? relay += 1 : individual += 1
    end
    { :individual => individual, :relay => relay }
  end

  def best_swim_for_event(event)
    eligible_heat_ids = event.related_heats.map(&:id)
    self.swims.where(:heat_id => eligible_heat_ids).order(:final_time_ms).first
  end
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
  before_action :authenticate

  def index
    @men = Athlete.active_men
    @women = Athlete.active_women
  end

  def show
    athlete
  end

  def new
    @athlete = Athlete.new
  end

  def create
    @athlete = Athlete.new(athlete_params)
    if @athlete.save
      flash[:success] = "#{@athlete.full_name} successfully created"
      redirect_to athletes_path
    else
      flash.now[:danger] = athlete_errors
      render 'new'
    end
  end

  def edit
    athlete
  end

  def update
    if athlete.update(athlete_params)
      flash['success'] = 'Updates were successful!'
      redirect_to athlete_path(athlete)
    else
      flash.now['danger'] = athlete_errors
      render 'edit'
    end
  end

  def destroy
    if athlete.destroy
      flash['success'] = 'Successful deletion!'
      redirect_to athletes_path
    else
      flash.now['danger'] = athlete_errors
      render 'edit'
    end
  end

  private

  def athlete
    @athlete ||= Athlete.find(params[:id])
  end

  def athlete_errors
    @athlete.errors.full_messages.join('. ')
  end

  def athlete_params
    params.require(:athlete).permit(:first_name, :last_name, :status, :gender)
  end
end

app/views/athletes/_form_fields.html.erb
<%= f.input :first_name, :label => false, :wrapper_html => {:class => "form-group"}, :input_html => {:class => "form-control", :placeholder => "First name"} %>
<%= f.input :last_name, :label => false, :wrapper_html => {:class => "form-group"}, :input_html => {:class => "form-control", :placeholder => "Last name"} %>
<%= f.input :status, :collection => f.object.class::STATUS_LIST, :include_blank => false, :label => false, :wrapper_html => {:class => "form-group"}, :input_html => {:class => "form-control"} %>
<%= f.input :gender, :collection => f.object.class::GENDER_LIST, :prompt => 'select a gender...', :label => false, :wrapper_html => {:class => "form-group"}, :input_html => {:class => "form-control"} %>

app/views/athletes/edit.html.erb
<h1>Edit Athlete</h1>

<div class="col-xs-12 col-sm-6">
  <%= simple_form_for @athlete do |f| %>
    <%= render 'form_fields', :f => f %>
    <%= f.button :submit, 'Save changes', :class => 'btn btn-info' %>
    <%= link_to 'Cancel changes', @athlete, :class => 'btn btn-danger' %>
  <% end %>
</div>

app/views/athletes/index.html.erb
<div class="row">
  <%= link_to 'Add an athlete', new_athlete_path, {:class => 'btn btn-info'} %>
</div>
<div class="row">
  <div class="col-xs-6">
    <h3>Women:</h3>
    <ul class="list-unstyled">
      <% @women.each do |athlete| %>
        <li><%= link_to athlete.full_name, athlete %></li>
      <% end %>
    </ul>
  </div>
  <div class="col-xs-6">
    <h3>Men:</h3>
    <ul class="list-unstyled">
      <% @men.each do |athlete| %>
        <li><%= link_to athlete.full_name, athlete %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/athletes/new.html.erb
<h1>New Athlete</h1>
<div class="col-xs-12 col-sm-6">
  <%= simple_form_for @athlete do |f| %>
    <%= render 'form_fields', :f => f %>
    <%= f.button :submit, :class => 'btn btn-info' %>
    <%= link_to 'Cancel', athletes_path, :class => 'btn btn-danger' %>
  <% end %>
</div>

app/views/athletes/show.html.erb
<h1><%= @athlete.full_name %></h1>
<%= link_to 'Edit athlete', edit_athlete_path(@athlete), :class => 'btn btn-info' %>
<%= link_to 'Delete athlete', @athlete, :method => :delete, :class => 'btn btn-danger', :"data-confirm" => "Are you sure you want to delete #{@athlete.full_name}" %>