config/routes.rb
Rails.application.routes.draw do

  root 'meets#index'

  get 'sign_up' => 'users#new', :as => 'sign_up'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'

  resources :users, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]

  resources :athletes
  resources :meets, :except => [:edit, :update] do
    member do
      get 'pdf'
      get 'csv'
    end
  end
  resources :heats, :only => [:show, :update]
end

app/models/meet.rb
class Meet < ActiveRecord::Base
  has_many :heats
  has_many :swims, :through => :heats

  validates_presence_of :opponent
  validates_presence_of :competition_date

  default_scope { order 'competition_date DESC' }

  def title
    format(
      '%s %s',
      competition_date.to_s(:db), opponent.titleize
    )
  end

  def pdf_filename
    format(
      '%s.pdf',
      title.gsub(/\s|-/, '_')
    )
  end

  def csv_filename
    format(
      '%s.csv',
      title.gsub(/\s|-/, '_')
    )
  end

  def final?
    heats.any? do |heat|
      heat.swims.any? { |swim| swim.final_time_ms.present? }
    end
  end
end

app/controllers/meets_controller.rb
class MeetsController < ApplicationController
  before_action :authenticate

  def index
    @meets = Meet.all
  end

  def show
    meet
  end

  def pdf
    pdf = MeetPdfGenerator.new(meet: meet).render!
    send_data pdf, :filename => meet.pdf_filename, :type => 'application/pdf'
  end

  def csv
    csv = MeetCsvGenerator.new(meet: meet, options: {:col_sep => ','}).render!
    send_data csv, :filename => meet.csv_filename, :type => 'application/csv'
  end

  def new
    @meet = Meet.new
  end

  def create
    ## TODO: extract this logic perhaps
    @meet = Meet.create(meet_params)

    # create a heat for every event
    Event.all.each do |event|
      entry_limit = if event.varsity
        (params[:meet][:entry_limit] || 3).to_i
      else
        8
      end

      @meet.heats.create(
        :event => event,
        :entry_limit => event.relay ? entry_limit * 4 : entry_limit
      )
    end

    redirect_to meet_path(@meet)
  end

  def destroy
    fail 'pending'
  end

  private

  def meet
    @meet ||= Meet.find(params[:id])
  end

  def meet_params
    params.require(:meet).permit(:opponent, :competition_date)
  end

end

app/views/meets/index.html.erb
<div class="row">
  <%= link_to 'Create a new meet', new_meet_path, {:class => 'btn btn-info'} %>
</div>
<br/>
<div class="row">
  <div class="col-xs-12">
    <ul class="list-unstyled">
      <% @meets.each do |meet| %>
        <li class="btn">
          <%= link_to meet.title, meet %>
        </li>
        <br/>
      <% end %>
    </ul>
</div>

app/views/meets/new.html.erb
<h1>New Meet</h1>
<div class="col-xs-12 col-sm-6">
  <%= simple_form_for @meet do |f| %>
    <%= f.input :opponent, :wrapper_html => {:class => "form-group"}, :input_html => {:class => "form-control",} %>
    <%= f.input :competition_date, :as => :date, :wrapper_html => {:class => "form-group"}, :input_html => {:class => "form-control"} %>
    <div class="input entry_limit form-group">
      <label for="entry_limit">Entry limit per heat</label>
      <input id="entry_limit" class="form-control" name="meet[entry_limit]" type="number" value="3">
    </div>
    <%= f.button :submit, 'Create meet', :class => 'btn btn-info' %>
    <%= link_to 'Cancel', meets_path, :class => 'btn btn-danger' %>
  <% end %>
</div>

app/views/meets/show.html.erb
<h1>
  <%= @meet.title %>
  <a class="btn btn-info" href="<%= pdf_meet_path(@meet) %>">meet pdf <i class="fa fa-cloud-download"></i></a>
  <a class="btn btn-info" href="<%= csv_meet_path(@meet) %>">meet spreadsheet <i class="fa fa-cloud-download"></i></a>
</h1>


<div class="row">
  <div class="edit-heat-view"></div>
</div>

<div class="row">
  <div class="list-group col-sm-6 col-xs-12">
    <% @meet.heats.women.each do |heat| %>
      <div id="heat-<%= heat.id %>-details">
        <%= render 'heats/details', :heat => heat %>
      </div>
    <% end %>
  </div>

  <div class="list-group col-sm-6 col-xs-12">
    <% @meet.heats.men.each do |heat| %>
      <div id="heat-<%= heat.id %>-details">
        <%= render 'heats/details', :heat => heat %>
      </div>
    <% end %>
  </div>
</div>